In [ ]:
#17 варіант

In [1]:
!pip install numpy

In [ ]:
import numpy as np

In [2]:
# Створіть одновимірний масив (вектор) з числами, які є квадратами натуральних чисел, починаючи з 1, та виведіть його значення.
squares = [i**2 for i in range(1, 11)]
print(squares)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [3]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями випадкових цілих чисел від 1 до 5.
import random
matrix = [[random.randint(1, 5) for _ in range(3)] for _ in range(3)]
print(matrix)


[[3, 1, 5], [5, 4, 5], [3, 4, 2]]


In [4]:
# Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 5 та знайдіть максимальне значення за рядком.
matrix = [[random.randint(1, 5) for _ in range(3)] for _ in range(3)]
max_in_rows = [max(row) for row in matrix]
print(matrix)
print(max_in_rows)


[[2, 5, 4], [3, 4, 4], [5, 5, 2]]
[5, 4, 5]


In [5]:
# Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 10 та знайдіть вектор-стовпчик, що містить мінімальні елементи в кожному рядку.
import random
matrix = [[random.uniform(0, 10) for _ in range(3)] for _ in range(3)]
min_in_rows = [min(row) for row in matrix]
print(matrix)
print(min_in_rows)


[[5.773320327157658, 4.960149550117482, 4.968894434535497], [8.324338458687157, 0.33117350724815364, 1.039768515760825], [7.058454339764623, 3.2755444157738633, 4.306344302362207]]
[4.960149550117482, 0.33117350724815364, 3.2755444157738633]


In [6]:
# Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та множення.
array1 = [random.uniform(0, 1) for _ in range(6)]
array2 = [random.uniform(0, 1) for _ in range(6)]

addition = [a + b for a, b in zip(array1, array2)]
subtraction = [a - b for a, b in zip(array1, array2)]
multiplication = [a * b for a, b in zip(array1, array2)]

print(array1)
print(array2)
print(addition)
print(subtraction)
print(multiplication)


[0.3472636246593175, 0.48736976776937335, 0.8822399846462561, 0.5595045856079981, 0.5073319574945668, 0.815384996429831]
[0.14111530587006105, 0.5891583021141145, 0.4032954436760513, 0.15754715496981853, 0.624309863786384, 0.18351759363549025]
[0.48837893052937853, 1.0765280698834878, 1.2855354283223073, 0.7170517405778166, 1.131641821280951, 0.9989025900653212]
[0.20614831878925644, -0.10178853434474111, 0.4789445409702048, 0.40195743063817957, -0.11697790629181715, 0.6318674027943407]
[0.04900421261134566, 0.2871379448807543, 0.3558033660366645, 0.08814835565510737, 0.31673234527791255, 0.14963749243128538]


In [7]:
# Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 0 до 10 та знайдіть їх добуток.
matrix1 = [[random.randint(0, 10) for _ in range(4)] for _ in range(4)]
matrix2 = [[random.randint(0, 10) for _ in range(4)] for _ in range(4)]

product = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]

print(matrix1)
print(matrix2)
print(product)


[[7, 9, 2, 7], [4, 0, 5, 5], [4, 6, 3, 9], [7, 4, 10, 2]]
[[2, 6, 2, 1], [8, 2, 7, 4], [8, 9, 4, 6], [5, 3, 4, 8]]
[[137, 99, 113, 111], [73, 84, 48, 74], [125, 90, 98, 118], [136, 146, 90, 99]]


In [8]:
# Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.

matrix1 = [[random.randint(1, 4) for _ in range(2)] for _ in range(3)]
matrix2 = [[random.randint(1, 4) for _ in range(4)] for _ in range(2)]

product = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]

print(matrix1)
print(matrix2)
print(product)


[[1, 4], [3, 3], [1, 1]]
[[1, 4, 4, 4], [2, 1, 4, 2]]
[[9, 8, 20, 12], [9, 15, 24, 18], [3, 5, 8, 6]]


In [9]:
# Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.

matrix1 = [[random.randint(1, 4) for _ in range(2)] for _ in range(3)]
matrix2 = [[random.randint(1, 4) for _ in range(4)] for _ in range(2)]

product = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]

print(matrix1)
print(matrix2)
print(product)


[[1, 3], [4, 4], [3, 2]]
[[4, 2, 3, 1], [3, 3, 3, 3]]
[[13, 11, 12, 10], [28, 20, 24, 16], [18, 12, 15, 9]]


In [11]:
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.

import numpy as np

matrix = [[random.randint(1, 8) for _ in range(2)] for _ in range(2)]
matrix_np = np.array(matrix)

# Перевірка, чи матриця є оберненою (визначник не нульовий)
if np.linalg.det(matrix_np) != 0:
    inverse_matrix = np.linalg.inv(matrix_np)
else:
    inverse_matrix = "Матриця не має оберненої матриці (визначник дорівнює нулю)."

print(matrix)
print(inverse_matrix)


[[6, 2], [4, 5]]
[[ 0.22727273 -0.09090909]
 [-0.18181818  0.27272727]]


In [12]:
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.
import random
import numpy as np

matrix = [[random.randint(1, 8) for _ in range(2)] for _ in range(2)]
matrix_np = np.array(matrix)

# Перевірка, чи матриця є оберненою (визначник не нульовий)
if np.linalg.det(matrix_np) != 0:
    inverse_matrix = np.linalg.inv(matrix_np)
else:
    inverse_matrix = "Матриця не має оберненої матриці (визначник дорівнює нулю)."

print(matrix)
print(inverse_matrix)


[[1, 7], [6, 3]]
[[-0.07692308  0.17948718]
 [ 0.15384615 -0.02564103]]


In [13]:
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.
import random

matrix = [[random.randint(0, 1) for _ in range(3)] for _ in range(3)]
transposed_matrix = [[matrix[j][i] for j in range(3)] for i in range(3)]

print(matrix)
print(transposed_matrix)


[[0, 0, 0], [1, 1, 0], [1, 1, 0]]
[[0, 1, 1], [0, 1, 1], [0, 0, 0]]


In [14]:
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import random
import numpy as np

# Створення матриці 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

# Створення вектора 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

# Обчислення добутку матриці на вектор
product = np.dot(matrix, vector)

print(matrix)
print(vector)
print(product)


[[0.03595049 0.83948438 0.7762636  0.49183629]
 [0.16463357 0.27254534 0.14271596 0.89004026]
 [0.86471522 0.74735414 0.76984944 0.96774357]]
[[5]
 [6]
 [9]
 [3]]
[[13.67854001]
 [ 6.41300437]
 [18.63957662]]


In [15]:
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import random
import numpy as np

# Створення матриці 2x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 3))

# Створення вектора 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Обчислення добутку матриці на вектор
product = np.dot(matrix, vector)

print(matrix)
print(vector)
print(product)



[[ 4 10  3]
 [ 7  2  3]]
[[8]
 [8]
 [2]]
[[118]
 [ 78]]


In [16]:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
# та знайдіть суму елементів діагоналі для обох матриць (окремо).
import random
import numpy as np

# Створення двох матриць 2x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Обчислення суми елементів діагоналі для обох матриць
diagonal_sum1 = np.trace(matrix1)
diagonal_sum2 = np.trace(matrix2)

print(matrix1)
print("Сума діагоналі першої матриці:", diagonal_sum1)
print(matrix2)
print("Сума діагоналі другої матриці:", diagonal_sum2)


[[ 5  9]
 [10  9]]
Сума діагоналі першої матриці: 14
[[5 2]
 [5 4]]
Сума діагоналі другої матриці: 9


In [17]:
# Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму їх елементів.
import numpy as np

# Створення двох матриць 3x3 з випадковими дійсними числами від 0 до 1
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

# Обчислення суми елементів для обох матриць
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

print(matrix1)
print("Сума елементів першої матриці:", sum_matrix1)
print(matrix2)
print("Сума елементів другої матриці:", sum_matrix2)



[[0.51881572 0.86447159 0.21383714]
 [0.1441186  0.45931142 0.25047594]
 [0.16946122 0.60259707 0.05655051]]
Сума елементів першої матриці: 3.2796392257669216
[[0.78095847 0.79959296 0.42059564]
 [0.67884676 0.88709063 0.64979709]
 [0.09998588 0.53737533 0.0934764 ]]
Сума елементів другої матриці: 4.947719157356275


In [18]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5
# та знайдіть середнє геометричне значення елементів матриці.
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від -5 до 5
matrix = np.random.uniform(-5, 5, size=(3, 3))

# Обчислення середнього геометричного значення елементів матриці
# Додамо 5 до всіх елементів, щоб уникнути негативних значень
geometric_mean = np.exp(np.mean(np.log(matrix + 5)))

print(matrix)
print("Середнє геометричне значення елементів матриці:", geometric_mean)


[[ 2.26436336 -4.48586459  0.10846949]
 [ 1.95075772 -2.73529707  2.67563914]
 [ 1.5743539   2.44341449 -1.26732255]]
Середнє геометричне значення елементів матриці: 4.216284920793366


In [19]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1
# та знайдіть вектор-стовпчик, що містить кількість додатних елементів в кожному рядку матриці.
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

# Обчислення кількості додатних елементів в кожному рядку
positive_count = np.sum(matrix > 0, axis=1)

print(matrix)
print("Кількість додатніх елементів в кожному рядку:", positive_count)


[[0.74140803 0.80234763 0.32792306]
 [0.2056105  0.40109095 0.57233155]
 [0.900494   0.14790895 0.20526301]]
Кількість додатніх елементів в кожному рядку: [3 3 3]


У процесі виконання завдань було створено різноманітні матриці та вектори за допомогою випадкових чисел. Зокрема, було виконано такі основні дії:

1. **Створення матриць і векторів**: Матриці різних розмірів заповнювалися випадковими цілими та дійсними числами в заданих діапазонах.

2. **Обчислення характеристик матриць**: Для матриць обчислювалися суми елементів діагоналі, середнє геометричне значення, кількість додатних елементів у рядках, а також здійснювалися операції множення та додавання.

3. **Транспонування**: Виконувалося транспонування матриць, що дозволяло змінювати їх форму для подальших обчислень.

4. **Вектор-стовпчик**: Створено вектори, що відображають певні характеристики матриць, такі як кількість додатніх елементів.

Ці завдання демонструють основи роботи з масивами та матрицями в Python, використовуючи бібліотеку NumPy для виконання обчислень, що є важливим для математичних і наукових задач.